name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Change Owner of Container Working Directory
      run: chown root:root .
    - uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify --buildDrafts
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
